export const SYNONYMS: Record<string, string[]> = {
  cheese: ["paneer"],
  potato: ["aloo"],
  potatoes: ["aloo"],
  chickpea: ["channa", "chana"],
  chickpeas: ["channa", "chana"],
  spinach: ["saag", "palak"],
  lentil: ["dal"],
  lentils: ["dal"],
  yogurt: ["dahi", "raita"],
  bread: ["naan", "roti", "paratha", "kulcha", "bhatura", "puri"],
  rice: ["biryani", "pulao"],
  fudge: ["barfi"],
  cake: ["barfi"],
  cauliflower: ["gobi"],
  okra: ["bhindi"],
  eggplant: ["baingan"],
  peas: ["mutter", "matar"],
  shrimp: ["prawn"],
  goat: ["lamb"],
};

export const STOPWORDS = new Set([
  "i",
  "im",
  "want",
  "something",
  "some",
  "a",
  "an",
  "the",
  "and",
  "or",
  "with",
  "that",
  "is",
  "for",
  "to",
  "me",
  "please",
  "craving",
  "like",
  "really",
  "very",
  "bit",
  "little",
  "of",
  "in",
  "on",
]);

export const NEGATION_WORDS = new Set(["not", "no", "non", "without"]);
